(* generated by dune *)

(** @canonical F_parser.Formula *)
module Formula = F_parser__Formula

(** @canonical F_parser.Lexer *)
module Lexer = F_parser__Lexer

(** @canonical F_parser.Misc *)
module Misc = F_parser__Misc

(** @canonical F_parser.Parser *)
module Parser = F_parser__Parser

module F_parser__ = struct end
[@@deprecated "this module is shadowed"]
